name: Tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Test
        run: npm test

      - name: Monitor coverage
        uses: devmasx/coverage-check-action@v1.1.0
        with:
          type: lcov
          github_token: ${{ secrets.GITHUB_TOKEN }}
          result_path: coverage/example.lcov
          min_coverage: 90
